// Every user-visible string of the app, in one place, Thai-first.
// Splitting them out keeps components free of literals and gives a future second language
// a single file to work against.
export const strings = {
  listTitle: "สถานีชาร์จใกล้ฉัน",
  rankedByCostPrefix: "จัดอันดับตามที่จ่ายจริง · ",
  areaFallbackSuffix: " · ใช้พื้นที่กรุงเทพฯ แทนตำแหน่งจริง",
  cacheSuffix: " · ข้อมูลจากแคช",
  retry: "ลองอีกครั้ง",
  locating: "กำลังหาสถานีใกล้คุณ…",
  noMatches: "ไม่พบสถานีที่ตรงเงื่อนไข — ลองขยายรัศมีหรือลดกำลังไฟขั้นต่ำ",
  loadFailed: "โหลดข้อมูลไม่สำเร็จ",
  countSuffix: " สถานี",

  sortCheapest: "ถูกสุด",
  sortNearest: "ใกล้สุด",
  radiusSuffix: " กม.",
  anyPower: "ทุกกำลังไฟ",
  minPowerPrefix: "≥ ",
  minPowerSuffix: " kW",
  allNetworks: "ทุกเครือข่าย",

  energyToAdd: "พลังงานที่ต้องเติม",
  energyPlaceholder: "ตามโปรไฟล์รถ",
  energyUnit: "kWh",
  useProfileValues: "ใช้ค่าโปรไฟล์รถ",
  profileButtonPrefix: "โปรไฟล์รถ: ",
  edit: "แก้ไข",

  unknownPrice: "ไม่ทราบราคา",
  arrivalPrefix: "ถึง ~",
  staleWarning: "ราคาอาจไม่เป็นปัจจุบัน",
  costPrefix: "≈ ",
  costSuffix: " ฿",
  unitPerKwh: "หน่วย",
  unitPerHour: "ชม.",
  unitPerMinute: "นาที",
  metreSuffix: " ม.",
  kilometreSuffix: " กม.",

  profileTitle: "โปรไฟล์รถ",
  profileHint: "ใช้กรองหัวชาร์จที่ใช้ได้กับรถคุณ และคำนวณพลังงานที่ต้องเติมต่อหนึ่งเซสชัน",
  connectorSection: "หัวชาร์จ",
  batteryLabel: "ความจุแบตเตอรี่",
  socFromLabel: "เริ่มชาร์จที่",
  socToLabel: "ชาร์จถึง",
  batteryUnit: "kWh",
  percentUnit: "%",
  save: "บันทึก",
  cancel: "ยกเลิก",
  profileFootnote: "ค่าที่ไม่สมเหตุสมผลจะถูกแทนด้วยค่าเริ่มต้น",
  defaultProfileNote: "CCS2 · 30 kWh · 20→80%",

  back: "← กลับ",
  tariffSection: "เรตที่ใช้",
  powerBandLabel: "ช่วงกำลังไฟ",
  windowLabel: "ช่วงตัวคูณราคา",
  flatAllDay: "ราคาเดียวทั้งวัน",
  peakLabel: "peak",
  offPeakLabel: "off-peak",
  offPeakSuffix: " นอกช่วงนั้น",
  weekdays: "จ.–ศ.",
  weekend: "ส.–อา.",
  everyDay: "ทุกวัน",
  dateUnknown: "ไม่ระบุวันที่ตรวจ",
  idleFeeLabel: "ค่าจอดหลังชาร์จเสร็จ",
  graceSuffix: " นาที",
  idlePerMinuteSuffix: " ฿/นาที",
  idlePerHourSuffix: " ฿/ชม.",
  afterGracePrefix: "หลังผ่อนผัน ",
  trustSection: "ความน่าเชื่อถือของราคา",
  checkedAtPrefix: "ตรวจล่าสุด ",
  evidencePrimary: "หน้าผู้ให้บริการ",
  evidenceSecondary: "สื่อ/ประกาศสาธารณะ",
  evidencePrefix: "ที่มา: ",
  hardwareSection: "หัวจ่ายและที่ตั้ง",
  openingHoursLabel: "เวลาเปิด",
  openingHoursUnknown: "ไม่ระบุ",
  addressLabel: "ที่อยู่",
  addressUnknown: "ไม่ระบุ",
  energyUsedPrefix: "พลังงาน ",
  noTariffNotice: "ยังไม่มีข้อมูลเรตของเครือข่ายนี้ จึงไม่แสดงราคา",
  navigate: "นำทาง",
  openNetworkApp: "เปิดแอปเครือข่าย",
  viewSource: "ดูแหล่งอ้างอิงราคา",
  sourceUnknown: "ไม่มีลิงก์แหล่งอ้างอิง",
  distanceLabel: "ระยะทาง",
  arrivalLabel: "ถึงประมาณ",
} as const;
